const mongoose = require('mongoose');
const bcrypt = require('bcrypt');
const User = require('./models/User');
require('dotenv').config();

const doctorsData = [
  {
    name: "Dr. Priya Shah",
    email: "priya.shah@caremate.com",
    password: "123456",
    role: "doctor",
    specialization: "Cardiologist",
    experience: 15,
    consultationFee: 1500,
    location: "Bodakdev, Ahmedabad",
    hospital: "Zydus Hospital",
    rating: 4.9,
    patientsCount: 124,
    verified: true,
    available: true,
    image: "/uploads/doctors/doctor12.jpg",
    bio: "Senior Consultant Cardiologist with vast experience in interventional cardiology.",
    education: "MD, DM (Cardiology) - AIIMS",
    availability: "Mon-Fri, 9am - 5pm",
    city: "Ahmedabad",
    state: "Gujarat"
  },
  {
    name: "Dr. Rajesh Patel",
    email: "rajesh.patel@caremate.com",
    password: "123456",
    role: "doctor",
    specialization: "Neurologist",
    experience: 12,
    consultationFee: 2000,
    location: "Science City, Ahmedabad",
    hospital: "CIMS Hospital",
    rating: 4.8,
    patientsCount: 98,
    verified: true,
    available: true,
    image: "/uploads/doctors/doctor2.jpg",
    bio: "Specialist in neurodegenerative disorders and stroke management.",
    education: "MD, DM (Neurology)",
    availability: "Tue-Sat, 10am - 6pm",
    city: "Ahmedabad",
    state: "Gujarat"
  },
  {
    name: "Dr. Nisha Trivedi",
    email: "nisha.trivedi@caremate.com",
    password: "123456",
    role: "doctor",
    specialization: "Pediatrician",
    experience: 8,
    consultationFee: 1000,
    location: "Kudasan, Gandhinagar",
    hospital: "Civil Hospital",
    rating: 4.9,
    patientsCount: 215,
    verified: true,
    available: true,
    image: "/uploads/doctors/doctor3.jpg",
    bio: "Dedicated to providing compassionate care for newborns and children.",
    education: "MBBS, DCH (Pediatrics)",
    availability: "Mon-Sat, 8am - 4pm",
    city: "Gandhinagar",
    state: "Gujarat"
  },
  {
    name: "Dr. Kunal Mehta",
    email: "kunal.mehta@caremate.com",
    password: "123456",
    role: "doctor",
    specialization: "Dermatologist",
    experience: 20,
    consultationFee: 1200,
    location: "Prahladnagar, Ahmedabad",
    hospital: "Sterling Hospital",
    rating: 4.7,
    patientsCount: 156,
    verified: true,
    available: true,
    image: "/uploads/doctors/doctor4.jpg",
    bio: "Expert in clinical and cosmetic dermatology with 20 years of practice.",
    education: "MD (Dermatology)",
    availability: "Mon-Wed, 10am - 7pm",
    city: "Ahmedabad",
    state: "Gujarat"
  },
  {
    name: "Dr. Vikram Rathod",
    email: "vikram.rathod@caremate.com",
    password: "123456",
    role: "doctor",
    specialization: "Neurologist",
    experience: 22,
    consultationFee: 1500,
    location: "Science City Road, Ahmedabad",
    hospital: "CIMS Hospital",
    rating: 4.9,
    patientsCount: 2200,
    verified: true,
    available: true,
    image: "/uploads/doctors/doctor5.jpg",
    bio: "Expert in stroke management and epilepsy treatment.",
    education: "MD (Medicine), DM (Neurology)",
    availability: "Mon-Fri (04:00 PM - 08:00 PM)",
    city: "Ahmedabad",
    state: "Gujarat"
  },
  {
    name: "Dr. Neha Gupta",
    email: "neha.gupta@caremate.com",
    password: "123456",
    role: "doctor",
    specialization: "Dermatologist",
    experience: 10,
    consultationFee: 700,
    location: "Prahladnagar, Ahmedabad",
    hospital: "Sterling Hospital",
    rating: 4.6,
    patientsCount: 1100,
    verified: true,
    available: true,
    image: "/uploads/doctors/doctor6.jpg",
    bio: "Clinical and cosmetic dermatology specialist.",
    education: "MD (Dermatology)",
    availability: "Daily (10:00 AM - 02:00 PM)",
    city: "Ahmedabad",
    state: "Gujarat"
  },
  {
    name: "Dr. Sameer Joshi",
    email: "sameer.joshi@caremate.com",
    password: "123456",
    role: "doctor",
    specialization: "General Physician",
    experience: 25,
    consultationFee: 500,
    location: "Sector 7, Gandhinagar",
    hospital: "Civil Hospital",
    rating: 4.5,
    patientsCount: 5000,
    verified: true,
    available: true,
    image: "/uploads/doctors/doctor7.jpg",
    bio: "Family physician with focus on preventive care.",
    education: "MBBS, MD (General Medicine)",
    availability: "Mon-Sat (08:00 AM - 02:00 PM)",
    city: "Gandhinagar",
    state: "Gujarat"
  },
  {
    name: "Dr. Kavita Desai",
    email: "kavita.desai@caremate.com",
    password: "123456",
    role: "doctor",
    specialization: "ENT Specialist",
    experience: 14,
    consultationFee: 650,
    location: "Sector 21, Gandhinagar",
    hospital: "Apollo Clinic",
    rating: 4.7,
    patientsCount: 1400,
    verified: true,
    available: true,
    image: "/uploads/doctors/doctor20.jpg",
    bio: "Expert in hearing disorders and sinus surgeries.",
    education: "MS (ENT)",
    availability: "Tue-Sat (05:00 PM - 09:00 PM)",
    city: "Gandhinagar",
    state: "Gujarat"
  },
  {
    name: "Dr. Rahul Mishra",
    email: "rahul.mishra@caremate.com",
    password: "123456",
    role: "doctor",
    specialization: "Hematologist",
    experience: 11,
    consultationFee: 1100,
    location: "Vastrapur, Ahmedabad",
    hospital: "HCG Cancer Centre",
    rating: 4.8,
    patientsCount: 600,
    verified: true,
    available: true,
    image: "/uploads/doctors/doctor9.jpg",
    bio: "Specializing in blood disorders and bone marrow transplants.",
    education: "MD, DM (Clinical Haematology)",
    availability: "Mon-Wed (10:00 AM - 04:00 PM)",
    city: "Ahmedabad",
    state: "Gujarat"
  },
  {
    name: "Dr. Anjali Mehta",
    email: "anjali.mehta@caremate.com",
    password: "123456",
    role: "doctor",
    specialization: "Infertility Specialist",
    experience: 9,
    consultationFee: 1500,
    location: "Navrangpura, Ahmedabad",
    hospital: "CIMS Fertility Center",
    rating: 4.9,
    patientsCount: 500,
    verified: true,
    available: true,
    image: "/uploads/doctors/doctor10.jpg",
    bio: "IVF expert helping couples achieve their parenthood dreams.",
    education: "DNB (OBG), Fellowship in Reproductive Medicine",
    availability: "Mon-Sat (11:00 AM - 05:00 PM)",
    city: "Ahmedabad",
    state: "Gujarat"
  },
  {
    name: "Dr. Alok Pandey",
    email: "alok.pandey@caremate.com",
    password: "123456",
    role: "doctor",
    specialization: "Cardiologist",
    experience: 20,
    consultationFee: 1800,
    location: "Sector 11, Gandhinagar",
    hospital: "Apex Heart Hospital",
    rating: 4.9,
    patientsCount: 3000,
    verified: true,
    available: true,
    image: "/uploads/doctors/doctor11.jpg",
    bio: "Senior interventional cardiologist and researcher.",
    education: "MD, DM, FACC",
    availability: "Mon-Thu (09:00 AM - 03:00 PM)",
    city: "Gandhinagar",
    state: "Gujarat"
  },
  {
    name: "Dr. Shweta Singh",
    email: "shweta.singh@caremate.com",
    password: "123456",
    role: "doctor",
    specialization: "Dermatologist",
    experience: 7,
    consultationFee: 900,
    location: "South Bopal, Ahmedabad",
    hospital: "Skin & Soul Clinic",
    rating: 4.7,
    patientsCount: 850,
    verified: true,
    available: true,
    image: "/uploads/doctors/doctor12.jpg",
    bio: "Focus on aesthetic dermatology and laser treatments.",
    education: "MD (Skin & VD)",
    availability: "Wed-Sun (12:00 PM - 07:00 PM)",
    city: "Ahmedabad",
    state: "Gujarat"
  },
  {
    name: "Dr. Manoj Kumar",
    email: "manoj.kumar@caremate.com",
    password: "123456",
    role: "doctor",
    specialization: "General Physician",
    experience: 30,
    consultationFee: 400,
    location: "Maninagar, Ahmedabad",
    hospital: "L.G. Hospital",
    rating: 4.6,
    patientsCount: 10000,
    verified: true,
    available: true,
    image: "/uploads/doctors/doctor1.jpg",
    bio: "Veteran physician with decades of clinical experience.",
    education: "MBBS",
    availability: "Daily (08:00 AM - 12:00 PM)",
    city: "Ahmedabad",
    state: "Gujarat"
  },
  {
    name: "Dr. Pooja Bajaj",
    email: "pooja.bajaj@caremate.com",
    password: "123456",
    role: "doctor",
    specialization: "Pediatrician",
    experience: 6,
    consultationFee: 500,
    location: "Infocity, Gandhinagar",
    hospital: "Children's Health Clinic",
    rating: 4.8,
    patientsCount: 400,
    verified: true,
    available: true,
    image: "/uploads/doctors/doctor14.jpg",
    bio: "Passionate about child health and developmental milestones.",
    education: "MD (Pediatrics)",
    availability: "Mon-Fri (10:00 AM - 04:00 PM)",
    city: "Gandhinagar",
    state: "Gujarat"
  },
  {
    name: "Dr. Sanvi Gupta",
    email: "sanvi.gupta@caremate.com",
    password: "123456",
    role: "doctor",
    specialization: "Orthopedist",
    experience: 19,
    consultationFee: 1300,
    location: "Bodakdev, Ahmedabad",
    hospital: "Shalby Hospital",
    rating: 4.8,
    patientsCount: 2500,
    verified: true,
    available: true,
    image: "/uploads/doctors/doctor32.jpg",
    bio: "Renowned orthopedic surgeon specializing in knee and hip replacements.",
    education: "MS (Ortho), M.Ch (Ortho)",
    availability: "Mon-Fri (11:00 AM - 05:00 PM)",
    city: "Ahmedabad",
    state: "Gujarat"
  },
  {
    name: "Dr. Ritu Sharma",
    email: "ritu.sharma@caremate.com",
    password: "123456",
    role: "doctor",
    specialization: "Gynecologist",
    experience: 16,
    consultationFee: 1100,
    location: "Kudasan, Gandhinagar",
    hospital: "Motherwell Hospital",
    rating: 4.9,
    patientsCount: 1800,
    verified: true,
    available: true,
    image: "/uploads/doctors/doctor20.jpg",
    bio: "Expert in maternal-fetal medicine and reproductive health.",
    education: "MBBS, MS, FICOG",
    availability: "Mon-Sat (10:00 AM - 02:00 PM)",
    city: "Gandhinagar",
    state: "Gujarat"
  },
  {
    name: "Dr. Faisal Khan",
    email: "faisal.khan@caremate.com",
    password: "123456",
    role: "doctor",
    specialization: "ENT Specialist",
    experience: 13,
    consultationFee: 750,
    location: "Paldi, Ahmedabad",
    hospital: "SVP Hospital",
    rating: 4.7,
    patientsCount: 1200,
    verified: true,
    available: true,
    image: "/uploads/doctors/doctor17.jpg",
    bio: "Specializing in micro-ear surgery and head-neck trauma.",
    education: "DLO, MS (ENT)",
    availability: "Tue-Sat (04:00 PM - 08:00 PM)",
    city: "Ahmedabad",
    state: "Gujarat"
  },
  {
    name: "Dr. Harish Patel",
    email: "harish.patel@caremate.com",
    password: "123456",
    role: "doctor",
    specialization: "Hematologist",
    experience: 5,
    consultationFee: 1400,
    location: "Gota, Ahmedabad",
    hospital: "Civil Hospital",
    rating: 4.5,
    patientsCount: 300,
    verified: true,
    available: true,
    image: "/uploads/doctors/doctor16.jpg",
    bio: "Dedicated to the treatment of benign and malignant blood disorders.",
    education: "MD, DM (Haematology)",
    availability: "Mon-Fri (09:00 AM - 03:00 PM)",
    city: "Ahmedabad",
    state: "Gujarat"
  },
  {
    name: "Dr. Nirav Soni",
    email: "nirav.soni@caremate.com",
    password: "123456",
    role: "doctor",
    specialization: "Neurologist",
    experience: 17,
    consultationFee: 1600,
    location: "Sector 6, Gandhinagar",
    hospital: "Gandhinagar Neuro Centre",
    rating: 4.8,
    patientsCount: 1600,
    verified: true,
    available: true,
    image: "/uploads/doctors/doctor15.jpg",
    bio: "Focused on neuro-muscular disorders and dementia care.",
    education: "MBBS, MD, DM (Neurology)",
    availability: "Mon-Sat (11:00 AM - 04:00 PM)",
    city: "Gandhinagar",
    state: "Gujarat"
  },
  {
    name: "Dr. Rohan Gupta",
    email: "rohan.gupta@caremate.com",
    password: "123456",
    role: "doctor",
    specialization: "Infertility Specialist",
    experience: 21,
    consultationFee: 2000,
    location: "Ellisbridge, Ahmedabad",
    hospital: "Bavishi Fertility Institute",
    rating: 4.9,
    patientsCount: 3500,
    verified: true,
    available: true,
    image: "/uploads/doctors/doctor16.jpg",
    bio: "Pioneer in reproductive endocrinology and advanced IVF techniques.",
    education: "MD (OBG), Fellowship in IVF (USA)",
    availability: "Wed-Sun (10:00 AM - 06:00 PM)",
    city: "Ahmedabad",
    state: "Gujarat"
  }
];

const seedDoctors = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB for seeding...");

    // Remove existing doctors to avoid duplicates during repeat runs
    // Warning: This will delete users with role "doctor"
    await User.deleteMany({ role: "doctor" });
    console.log("Cleared existing doctors collection.");

    const hashedPassword = await bcrypt.hash("123456", 10);

    const doctorsToInsert = doctorsData.map(doc => ({
      ...doc,
      password: hashedPassword,
      isApproved: true, // Ensuring they can login
      status: "approved"
    }));

    await User.insertMany(doctorsToInsert);
    console.log(`✅ Successfully seeded ${doctorsToInsert.length} doctors!`);

    process.exit(0);
  } catch (error) {
    console.error("❌ Seeding Error:", error);
    process.exit(1);
  }
};

seedDoctors();
